# Generated by Django 2.2 on 2019-12-16 11:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0003_auto_20191216_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewsmodel',
            name='news_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
