# Generated by Django 2.2 on 2019-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0004_auto_20191216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewsmodel',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpeg', upload_to='thumbnail/'),
        ),
    ]
