# Generated by Django 2.2 on 2019-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0005_addnewsmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewsmodel',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnail/'),
        ),
    ]
