# Generated by Django 2.2 on 2019-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0006_auto_20191217_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewsmodel',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='thumbnail/'),
        ),
    ]
