# Generated by Django 2.2 on 2019-12-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0007_auto_20191217_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnewsmodel',
            name='thumbnail',
        ),
    ]
