# Generated by Django 2.2 on 2019-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_categories', '0008_remove_addnewsmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
